### PR TITLE
add wireguard to kernel source (module)

### PR DESCRIPTION
**Pull request by hughobrien**
Would like to get some thoughts on adding wireguard to the k3os kernel, please let me know if this is a) desired or b) the right approach.

We may want to pin to a wireguard commit.

Thanks for k3!

### CODE REVIEW

**Comment by nazarewk** [comment]
would be great to see this finished and merged

**Comment by bhale** [comment]
Very nice! Since Ubuntu 20.04 backported the 5.6 in-tree Wireguard to their kernel sources, it might be cleaner implementation to upgrade to that after they release and get it for "free." 

It looks like Alpine already has WG 1.0 userland tools, so installing those would be easy.

**Comment by hughobrien** [comment]
@bhale certainly cleaner that way. I'll leave this open in the mean time in case anyone wants to run their own build.

**Comment by dclark** [comment]
Thanks @hughobrien I've made a few tweaks to the patch to pin the wireguard release and set the version and repo in Dockerfile.dapper

https://github.com/dclark/k3os-kernel/tree/wireguard

[wireguard-patch.txt](https://github.com/rancher/k3os-kernel/files/4496500/wireguard-patch.txt)

**Comment by hughobrien** [comment]
Nice, PR to my fork if you like and I'll merge. Then this PR will have the lot.
Edit: Actually you've got the lot already. Maybe just PR to this repo.

**Comment by dclark** [comment]
@hughobrien https://github.com/hughobrien/k3os-kernel/pull/2

Edit: tidied up the pull request to merge automatically into your branch

**Comment by dweomer** [comment]
@hughobrien can I get you to rebase and squash this PR? 
Screen Shot 2020-04-28 at 11 46 58 AM

**Comment by hughobrien** [comment]
@dweomer done. @dclark 's commits were squashed in also so please share any kudos with him.

**Pull request merged**
