### PR TITLE
Ubuntu Focal 5.4.0-26.30

### PR DESCRIPTION
**Pull request by nazarewk**
Trying to compile 5.4 kernel so we get Wireguard support

### CODE REVIEW

**Comment by nazarewk** [comment]
Not sure why, but i am running out of disk space (consuming 18GB out of 20GB `/var/lib/docker` volume) when trying to compile this.

**Comment by dweomer** [comment]
@nazarewk I have got a branch for this on my home workstation what I cannot get to compile the wireguard bits, will push it up later today regardless of how broken it is.

For these changes, have you been able to get it to compile all modules?

**Comment by nazarewk** [comment]
No, i didn't compile it successfully yet, i'm green when compiling my own kernel, thought it would be way easier with earlier versions already working :)

Trying to tweak various stuff like:
- changing to `ubuntu:focal` base image (currently building),
- will try using `apt-get build-deps` in build image next

**Comment by nazarewk** [comment]
Well... i don't really know how to proceed with compiling 5.4 kernel, feel free to take over.

**Comment by dweomer** [comment]
> Well... i don't really know how to proceed with compiling 5.4 kernel, feel free to take over.

@nazarewk this won't make you feel any better but I have been struggling with this one too. The feedback loop sucks and the errors from the build aren't super indicative of the actual problem either.

**Comment by blaggacao** [comment]
Just noted there seems to be a hwe kernel branch in bionic:
https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/log/?h=hwe-5.4

**Comment by blaggacao** [comment]
It also looks focal doesn't yet provide a hwe kernel branch, see: https://askubuntu.com/a/1232325, the patches however act against the `debian.hwe` folder.

I just searched for `debian.hwe` in http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux_5.4.0-31.35.diff.gz (retrieved from [here](https://packages.ubuntu.com/focal/linux-source-5.4.0))- it's effectively not there. Am I missing something?

**Comment by blaggacao** [comment]
OK, didn't see [this](https://github.com/rancher/k3os-kernel/compare/focal/lts/5.4.0) sorry for the noise.

**Comment by dweomer** [comment]
Yep, sorry. This is superseded by the `focal/lts/5.4.0` branch that I pushed last week. Solved the build problems.

**Pull request closed without merging**
